version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/aws-devops-pgp
hooks:
  ApplicationStart:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root


