
---

version: 0.0
os: linux
files:
  - source: /app
    destination: /home/ec2-user/aws-devops-pgp/app
  - source: /config.py
    destination: /home/ec2-user/aws-devops-pgp/
  - source: /app.py
    destination: /home/ec2-user/aws-devops-pgp/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: root

